### ISSUE TITLE
Ask Tentang Karyakarsa API

### ISSUE THREAD

**Issue by zulfaza** [zulfahmi-ardiansah/eno-bening#1]
Ku mau bertanya bagaimana caranya memperoleh API karyakarsa, Ku sudah mencoba searching dan melihat web karyakarsa namun tidak menemukan link yang membahas tentang APInya, dan apakah ada dokumentasinya?? Terima kasih

**Comment by zulfahmi-ardiansah** [comment]
Memang gak ada dokumentasi dan pembahasan soal API nya sih, tapi kalau diinspect element lalu ke tab network ada beberapa api untuk dapat data postingan karya karsa. Kalau disini contohnya https://api.karyakarsa.com/api/posts/enobening?page=1

**Comment by zulfaza** [comment]
owh oke terima kasih
